# Generated by Django 4.2.16 on 2024-12-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_detials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detials',
            name='description',
            field=models.CharField(max_length=5000),
        ),
    ]
